name: Build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and test"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test --stacktrace
      - name: Get Git hash
        id: get_git_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Rename Odin JAR with Git hash
        run: |
          for file in odin/build/libs/*.jar; do
            mv "$file" "${file%.jar}-${{ steps.get_git_hash.outputs.hash }}.jar"
          done
      - name: Rename OdinClient JAR with Git hash
        run: |
          for file in odinclient/build/libs/*.jar; do
            mv "$file" "${file%.jar}-${{ steps.get_git_hash.outputs.hash }}.jar"
          done

      - uses: actions/upload-artifact@v3
        name: Upload Odin
        with:
          name: "Odin Build"
          path: odin/build/libs/*-${{ steps.get_git_hash.outputs.hash }}.jar
      - uses: actions/upload-artifact@v3
        name: Upload OdinClient
        with:
          name: "OdinClient Build"
          path: odinclient/build/libs/*-${{ steps.get_git_hash.outputs.hash }}.jar
      - name: Test with Gradle
        run: ./gradlew test
      - uses: actions/upload-artifact@v3
        name: "Upload test report"
        if: ${{ !cancelled() }}
        with:
          name: "Test Results"
          path: build/reports/tests/test/
